### ISSUE TITLE
Chromedriver error?

### ISSUE THREAD

**Issue by ovhx** [hydino2085143/Discord-OTP-Forcer#1]
====== WebDriver manager ======
Current google-chrome version is 101.0.4951
Get LATEST chromedriver version for 101.0.4951 google-chrome
Driver [/home/colab/.wdm/drivers/chromedriver/linux64/101.0.4951.41/chromedriver] found in cache
main.py:15: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  driver = webdriver.Chrome(ChromeDriverManager().install())
Traceback (most recent call last):
  File "main.py", line 15, in <module>
    driver = webdriver.Chrome(ChromeDriverManager().install())
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/chrome/webdriver.py", line 73, in __init__
    service_log_path, service, keep_alive)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/chromium/webdriver.py", line 99, in __init__
    options=options)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 269, in __init__
    self.start_session(capabilities, browser_profile)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 360, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/webdriver.py", line 425, in execute
    self.error_handler.check_response(response)
  File "/usr/local/lib/python3.7/dist-packages/selenium/webdriver/remote/errorhandler.py", line 247, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally.
  (unknown error: DevToolsActivePort file doesn't exist)
  (The process started from chrome location /usr/bin/google-chrome is no longer running, so ChromeDriver is assuming that Chrome has crashed.)
Stacktrace:
#0 0x5579c4a04533 <unknown>
#1 0x5579c47631e8 <unknown>
#2 0x5579c478654a <unknown>
#3 0x5579c4781c4a <unknown>
#4 0x5579c47bcd0a <unknown>
#5 0x5579c47b6e33 <unknown>
#6 0x5579c478c71a <unknown>
#7 0x5579c478d875 <unknown>
#8 0x5579c4a48e1d <unknown>
#9 0x5579c4a4c751 <unknown>
#10 0x5579c4a3307e <unknown>
#11 0x5579c4a4d388 <unknown>
#12 0x5579c4a27fe0 <unknown>
#13 0x5579c4a69748 <unknown>
#14 0x5579c4a698c8 <unknown>
#15 0x5579c4a8370d <unknown>
#16 0x7fc7b21746db <unknown>

**Comment by hydino2085143** [comment]
What platform are you using? From the looks of it, you're using Linux. I have developed my script on a Windows machine, so I cannot solve this problem.

My script uses a Python package called [webdriver_manager](https://github.com/SergeyPirogov/webdriver_manager), which manages the installation of Chrome web drivers automatically. Your error is related to that package, so I suggest you raise this issue with the developer of it 🙂

**Comment by ovhx** [comment]
I'll try it on a Windows machine then and I will let you know

**Comment by ovhx** [comment]
Sorry for the late reply but yea it works on windows
