### ISSUE TITLE
'pip' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by Spaget09** [hydino2085143/Discord-OTP-Forcer#4]

**Comment by hydino2085143** [comment]
Do you have Python installed? If not, install it. This project needs python to run

If Python is installed, then try following this: https://stackoverflow.com/a/56678271/19195633

If there are no files in the Scripts directory, then follow this: https://stackoverflow.com/a/67768504/19195633

If it still doesn't work, then let me know
