### ISSUE TITLE
help

### ISSUE THREAD

**Issue by throwaway12345678910111** [hydino2085143/Discord-OTP-Forcer#6]
I got locked out of my account recently and I have 2 problems rn
1) i dont understand shit about how to download/ use this software so can someone give me a dumbed down version of what to do
2) my discord is acting up and wont let me use the 6 number 2FA so is there like some variables I can change to make it compatible with the 8 number 2FA

**Comment by hydino2085143** [comment]
Hi! Sorry for not responding, I'll get back to you in a few hours

**Comment by throwaway12345678910111** [comment]
thx i now have figured out how to use the software and about the email id and password I don't have the password but I do have the email and since I don't have the SMS 2fa I just want to know what to edit in the code so i can run it to do the 8 character codes

**Comment by hydino2085143** [comment]
This software needs you to have both the password and email of the account. Without it it won't work because it has to sign in using that. Could you try resetting your password?

And what device are you using for this? Windows 10? Android?

**Comment by throwaway12345678910111** [comment]
im using windows 10 and im doing this because I lost my password so couldn't I just delete the field that needs the password

**Comment by hydino2085143** [comment]
this program needs you to have the password, it won't work without it, because it won't be able to log in and start finding the 2fa code.

My advice to you is do a password reset for your account if possible. Otherwise your account is lost

**Comment by hydino2085143** [comment]
How's it going?
